USE master;
GO
ALTER DATABASE [TESTDB_ZUMSPIELEN] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

Restore Database[TestDB_zumSpielen] from Database_Snapshot = 'TestDB_zumSpielen_20221104_1231'
go

ALTER DATABASE [TESTDB_ZUMSPIELEN]
SET MULTI_USER
WITH ROLLBACK IMMEDIATE
GO