-- Restore einer Datenbank oder eines Tablespaces via RMAN.
-- Diese Datei ist eine Vorlage - im rman-Client ausführen.

/*
-- rman target /

-- 1) Was ist im Backup? (analog zu MSSQL RESTORE HEADERONLY / FILELISTONLY)
RMAN> LIST BACKUP OF DATABASE;
RMAN> LIST BACKUP OF DATAFILE 4;

-- 2) Restore Point-in-Time
RMAN> SHUTDOWN IMMEDIATE;
RMAN> STARTUP MOUNT;
RMAN> RUN {
    SET UNTIL TIME "TO_DATE('2026-07-27 10:00:00','YYYY-MM-DD HH24:MI:SS')";
    RESTORE DATABASE;
    RECOVER DATABASE;
};
RMAN> ALTER DATABASE OPEN RESETLOGS;

-- 3) Restore auf anderen Pfad (analog zu MSSQL WITH MOVE)
RMAN> RUN {
    SET NEWNAME FOR DATAFILE 1 TO '/neu/system01.dbf';
    SET NEWNAME FOR DATAFILE 3 TO '/neu/sysaux01.dbf';
    SET NEWNAME FOR DATAFILE 4 TO '/neu/users01.dbf';
    RESTORE DATABASE;
    SWITCH DATAFILE ALL;
    RECOVER DATABASE;
};

-- 4) Einzelnen Tablespace restaurieren (Rest bleibt online)
RMAN> SQL 'ALTER TABLESPACE USERS OFFLINE';
RMAN> RESTORE TABLESPACE USERS;
RMAN> RECOVER TABLESPACE USERS;
RMAN> SQL 'ALTER TABLESPACE USERS ONLINE';

-- 5) Nur ein Datafile
RMAN> SQL 'ALTER DATABASE DATAFILE 4 OFFLINE';
RMAN> RESTORE DATAFILE 4;
RMAN> RECOVER DATAFILE 4;
RMAN> SQL 'ALTER DATABASE DATAFILE 4 ONLINE';
*/
